version: "3.9"
services: 
  nginx:
    build: requirements/nginx/
    conatiner_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./website:/var/www/html"
    depends_on:
      - wordpress
    restart: always
    networks:
      - docker-network

networks:
  docker-network: