version: "3.7"
services: 
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/Users/aerragha/website:/var/www/html"
    # depends_on:
    #   - wordpress
    restart: always
    networks:
      - docker-network

networks:
  docker-network: