version: "3.7"
services:
  mariadb:
    build: requirements/mariadb/
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "data-vol:/var/lib/mysql"
    networks:
      - docker-network
    restart: always
    env_file:
      - .env

  wordpress:
    build: requirements/wordpress/
    image: wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - "web-vol:/var/www/html/wordpress"
    depends_on:
      - mariadb
    networks:
      - docker-network
    restart: always
    env_file:
      - .env

  nginx:
    build: requirements/nginx/
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - "web-vol:/var/www/html/wordpress"
    depends_on:
      - wordpress
    restart: always
    networks:
      - docker-network
    env_file:
      - .env

  adminer:
    build: requirements/bonus/adminer/
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - nginx
    networks:
      - docker-network
    restart: always

  redis:
    build: requirements/bonus/redis/
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    depends_on:
      - nginx
    networks:
      - docker-network
    restart: always
    env_file:
      - .env

  website:
    container_name: website
    build: requirements/bonus/website/
    image: website
    networks:
      - docker-network
    ports:
      - "3001:3001"
    restart: always
  
  ftp-server:
    build: requirements/bonus/ftp-server/
    image: ftp-server
    container_name: ftp-server
    volumes:
      - web-vol:/home/aerragha
    ports:
      - "21:21" # For commands
      - "20:20" # For data
      - "1024-1048:1024-1048"
    networks:
      - docker-network
    restart: always
    env_file:
      - .env

  cadvisor:
    build: requirements/bonus/cadvisor
    image: cadvisor
    container_name: cadvisor
    ports:
      - "7000:7000"
    networks:
        - docker-network
    restart: always
    env_file:
      - .env
  
networks:
  docker-network:

volumes:
  data-vol:
    driver_opts:
      type: none
      device: /home/aerragha/data/mariadb
      o: bind
  web-vol:
    driver_opts:
      type: none
      device: /home/aerragha/data/website
      o: bind
